version: '2'
services:
    web:
        build: .
        command: python -u app.py
        ports:
            -  "5000:5000"
        volumes:
            - .:/DockerFlaskProject
        links:
           - db
    db:
        image: mongo:3.0.2
        volumes:
           - "/data/db"
        ports:
            - "27017:27017"
    